### ISSUE TITLE
kms client no SetContext() methos

### ISSUE THREAD

**Issue by firetaker** [TencentCloud/tencentcloud-sdk-go#169] opened 2022-01-07 02:48 UTC
`# github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/kms/v20190118
../../vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/kms/v20190118/client.go:104:12: request.SetContext undefined (type *ArchiveKeyRequest has no field or method SetContext)
../../vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/kms/v20190118/client.go:166:12: request.SetContext undefined (type *AsymmetricRsaDecryptRequest has no field or method SetContext)
../../vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/kms/v20190118/client.go:230:12: request.SetContext undefined (type *AsymmetricSm2DecryptRequest has no field or method SetContext)
../../vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/kms/v20190118/client.go:290:12: request.SetContext undefined (type *BindCloudResourceRequest has no field or method SetContext)
../../vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/kms/v20190118/client.go:352:12: request.SetContext undefined (type *CancelKeyArchiveRequest has no field or method SetContext)
../../vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/kms/v20190118/client.go:410:12: request.SetContext undefined (type *CancelKeyDeletionRequest has no field or method SetContext)
../../vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/kms/v20190118/client.go:480:12: request.SetContext undefined (type *CreateKeyRequest has no field or method SetContext)
../../vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/kms/v20190118/client.go:544:12: request.SetContext undefined (type *CreateWhiteBoxKeyRequest has no field or method SetContext)
../../vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/kms/v20190118/client.go:604:12: request.SetContext undefined (type *DecryptRequest has no field or method SetContext)
../../vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/kms/v20190118/client.go:666:12: request.SetContext undefined (type *DeleteImportedKeyMaterialRequest has no field or method SetContext)
../../vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/kms/v20190118/client.go:666:12: too many errors

Compilation finished with exit code 2`

**Comment by firetaker** [comment] 2022-01-07 02:54
PS
github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/kms v1.0.326

**Comment by firetaker** [comment] 2022-01-07 03:03
fixed, just go get -v -u ...

**Comment by zqfan** [comment] 2022-01-08 09:26
sorry, it is caused by our mistake, a pr should be merged before autogen code is pushed, it is already fixed in newer version

**Closed by zqfan** 2022-01-08 09:26 UTC
